baseurl: "https://abndistro.com"
languageCode: "en-us"
title: "Abnormal Distributions"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    # - name: Projects
    #  url: "projects/"
    #  weight: 2
    - name: Docs
      url: "post/"
      weight: 3
    - name: Tags
      url: "tags/"
      weight: 4
    # - name: Subscribe
    #   url: "index.xml"

params:
  description: "Personal website of Danny Morris"
  footer: "[GitHub](https://github.com/dannymorris) | [LinkedIn](https://www.linkedin.com/in/drmorris87/) | [Email](mailto:usc00@hotmail.com)"

markup:
  goldmark:
    renderer:
      unsafe: true
