---
title: Basic usage of GluonTS for probabilistic, deep learning-based time series forecasting
author: Danny Morris
date: '2021-05-12'
output: 
  blogdown::html_page:
    toc: true
    highlight: pygments
slug: basic-usage-of-gluonts-for-time-series-forecasting-in-python
categories:
  - Python
  - Time Series
  - Data Science
  - Machine Learning
  - Deep Learning
tags:
  - Python
  - Time Series
  - Data Science
  - Machine Learning
  - Deep Learning
---

## Overview

GluonTS is a deep learning-based framework for probabilisitc time series modeling and forecasting. As mentioned in the [paper](https://arxiv.org/pdf/1906.05264.pdf), deep learning models improve upon traditional univariate models (e.g. Arima) with their ability to train a single, global model over an entire collection of time series. 

## Notebook

The use case shown in this notebook involves jointly training and forecasting 152 time series at monthly intervals. The data are originally in CSV format. 
The [DeepAR](https://arxiv.org/pdf/1704.04110.pdf) estimator is applied to the training data, and code for a faster [feedforward MLP](https://ts.gluon.ai/api/gluonts/gluonts.model.simple_feedforward.html) alternative is provided for reference at the end.

<script src="https://gist.github.com/dannymorris/7859f4bc04f8665cb93b72d0a2e48711.js"></script>

## Pseudocode

The following pseudocode represents the general workflow in the Jupyter notebook.

```
IMPORT packages
READ raw data
TRANSFORM raw data to wide format where each column is a time series
SPLIT training and testing data
TRANSFORM training and testing data to ListDataset format for GluonTS compatibility
DEFINE estimator (e.g. DeepAR)
TRAIN estimator jointly over all time series in training data
PREDICT values jointly for all time series in testing data
PRINT prediction accuracy metrics for each time series
PLOT predictions
```

## Takeaways from my experience getting started

- Training and inference for all 152 time series required about 2 minutes in total using the [DeepAR](https://ts.gluon.ai/api/gluonts/gluonts.model.deepar.html) estimator and CPUs provided by Google Colab. Using the simple [feedforward MLP](https://ts.gluon.ai/api/gluonts/gluonts.model.simple_feedforward.html) estimator, the total time was around 7 seconds.

- Simple API yet sparse documentation.

- Probabilistic forecast intervals combined with deep learning differentiate GluonTS from other machine learning algorithms which are only capable of producing point forecasts.

- Despite variance in scale and seasonality across all time series, impressive predictive accuracy was achieved without feature engineering or hyperparameter tuning.
